// src/questions.js
const questions = [
  { id: 1, title: 'Two Sum', url: 'https://leetcode.com/problems/two-sum/', checked: false, note: '', revision: false },
  { id: 2, title: 'Container With Most Water', url: 'https://leetcode.com/problems/container-with-most-water/', checked: false, note: '', revision: false },
  { id: 3, title: '3Sum', url: 'https://leetcode.com/problems/3sum/', checked: false },
  { id: 4, title: '4Sum', url: 'https://leetcode.com/problems/4sum/', checked: false },
  { id: 5, title: 'Trapping Rain Water', url: 'https://leetcode.com/problems/trapping-rain-water/', checked: false },
  { id: 6, title: 'Best Time to Buy and Sell Stock', url: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/', checked: false },
  { id: 7, title: 'Best Time to Buy and Sell Stock II', url: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/', checked: false },
  { id: 8, title: 'Best Time to Buy and Sell Stock III', url: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/', checked: false },
  { id: 9, title: 'Product of Array Except Self', url: 'https://leetcode.com/problems/product-of-array-except-self/', checked: false },
  { id: 10, title: 'Maximum Subarray', url: 'https://leetcode.com/problems/maximum-subarray/', checked: false },
  { id: 11, title: 'Maximum Product Subarray', url: 'https://leetcode.com/problems/maximum-product-subarray/', checked: false },
  { id: 12, title: 'Spiral Matrix', url: 'https://leetcode.com/problems/spiral-matrix/', checked: false },
  { id: 13, title: 'Rotate Image', url: 'https://leetcode.com/problems/rotate-image/', checked: false },
  { id: 14, title: 'Search in Rotated Sorted Array', url: 'https://leetcode.com/problems/search-in-rotated-sorted-array/', checked: false },
  { id: 15, title: 'Search in Rotated Sorted Array II', url: 'https://leetcode.com/problems/search-in-rotated-sorted-array-ii/', checked: false },
  { id: 16, title: 'Search for a Range', url: 'https://leetcode.com/problems/search-for-a-range/', checked: false },
  { id: 17, title: 'Median of Two Sorted Arrays', url: 'https://leetcode.com/problems/median-of-two-sorted-arrays/', checked: false },
  { id: 18, title: 'Find Peak Element', url: 'https://leetcode.com/problems/find-peak-element/', checked: false },
  { id: 19, title: 'Search a 2D Matrix', url: 'https://leetcode.com/problems/search-a-2d-matrix/', checked: false },
  { id: 20, title: 'Search a 2D Matrix II', url: 'https://leetcode.com/problems/search-a-2d-matrix-ii/', checked: false },
  { id: 21, title: 'Game of Life', url: 'https://leetcode.com/problems/game-of-life/', checked: false },
  { id: 22, title: 'Combination Sum', url: 'https://leetcode.com/problems/combination-sum/', checked: false },
  { id: 23, title: 'Combination Sum II', url: 'https://leetcode.com/problems/combination-sum-ii/', checked: false },
  { id: 24, title: 'Subsets', url: 'https://leetcode.com/problems/subsets/', checked: false },
  { id: 25, title: 'Subsets II', url: 'https://leetcode.com/problems/subsets-ii/', checked: false },
  { id: 26, title: 'Largest Rectangle in Histogram', url: 'https://leetcode.com/problems/largest-rectangle-in-histogram/', checked: false },
  { id: 27, title: 'Next Permutation', url: 'https://leetcode.com/problems/next-permutation/', checked: false },
  { id: 28, title: 'Permutations', url: 'https://leetcode.com/problems/permutations/', checked: false },
  { id: 29, title: 'Permutations II', url: 'https://leetcode.com/problems/permutations-ii/', checked: false },
  { id: 30, title: 'Substring with Concatenation of All Words', url: 'https://leetcode.com/problems/substring-with-concatenation-of-all-words/', checked: false },
  { id: 31, title: 'Jump Game', url: 'https://leetcode.com/problems/jump-game/', checked: false },
  { id: 32, title: 'Jump Game II', url: 'https://leetcode.com/problems/jump-game-ii/', checked: false },
  { id: 33, title: 'Longest Consecutive Sequence', url: 'https://leetcode.com/problems/longest-consecutive-sequence/', checked: false },
  { id: 34, title: 'Merge Intervals', url: 'https://leetcode.com/problems/merge-intervals/', checked: false },
  { id: 35, title: 'Insert Interval', url: 'https://leetcode.com/problems/insert-interval/', checked: false },
  { id: 36, title: 'Valid Sudoku', url: 'https://leetcode.com/problems/valid-sudoku/', checked: false },
  { id: 37, title: 'Sudoku Solver', url: 'https://leetcode.com/problems/sudoku-solver/', checked: false },
  { id: 38, title: 'N-Queens', url: 'https://leetcode.com/problems/n-queens/', checked: false },
  { id: 39, title: 'N-Queens II', url: 'https://leetcode.com/problems/n-queens-ii/', checked: false },
  { id: 40, title: 'Count of Smaller Numbers After Self', url: 'https://leetcode.com/problems/count-of-smaller-numbers-after-self/', checked: false },
  { id: 41, title: 'Minimum Window Substring', url: 'https://leetcode.com/problems/minimum-window-substring/', checked: false },
  { id: 42, title: 'Sliding Window Maximum', url: 'https://leetcode.com/problems/sliding-window-maximum/', checked: false },
  { id: 43, title: 'Palindromic Substrings', url: 'https://leetcode.com/problems/palindromic-substrings/', checked: false },
  { id: 44, title: 'Longest Palindromic Substring', url: 'https://leetcode.com/problems/longest-palindromic-substring/', checked: false },
  { id: 45, title: 'Longest Valid Parentheses', url: 'https://leetcode.com/problems/longest-valid-parentheses/', checked: false },
  { id: 46, title: 'Edit Distance', url: 'https://leetcode.com/problems/edit-distance/', checked: false },
  { id: 47, title: 'Distinct Subsequences', url: 'https://leetcode.com/problems/distinct-subsequences/', checked: false },
  { id: 48, title: 'Wildcard Matching', url: 'https://leetcode.com/problems/wildcard-matching/', checked: false },
  { id: 49, title: 'Regular Expression Matching', url: 'https://leetcode.com/problems/regular-expression-matching/', checked: false },
  { id: 50, title: 'Maximum Length of Repeated Subarray', url: 'https://leetcode.com/problems/maximum-length-of-repeated-subarray/', checked: false },
  { id: 51, title: 'Longest Increasing Subsequence', url: 'https://leetcode.com/problems/longest-increasing-subsequence/', checked: false },
  { id: 52, title: 'Longest Common Subsequence', url: 'https://leetcode.com/problems/longest-common-subsequence/', checked: false },
  { id: 53, title: 'Longest Palindromic Subsequence', url: 'https://leetcode.com/problems/longest-palindromic-subsequence/', checked: false },
  { id: 54, title: 'Maximum Subarray Sum with One Deletion', url: 'https://leetcode.com/problems/maximum-subarray-sum-with-one-deletion/', checked: false },
  { id: 55, title: 'Valid Mountain Array', url: 'https://leetcode.com/problems/valid-mountain-array/', checked: false },
  { id: 56, title: 'Minimum Path Sum', url: 'https://leetcode.com/problems/minimum-path-sum/', checked: false },
  { id: 57, title: 'Find First and Last Position of Element in Sorted Array', url: 'https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/', checked: false },
  { id: 58, title: 'Product of the Last K Numbers', url: 'https://leetcode.com/problems/product-of-the-last-k-numbers/', checked: false },
  { id: 59, title: 'Find All Duplicates in an Array', url: 'https://leetcode.com/problems/find-all-duplicates-in-an-array/', checked: false },
  { id: 60, title: 'Jump Game VI', url: 'https://leetcode.com/problems/jump-game-vi/', checked: false },
  { id: 61, title: 'Range Sum of Sorted Subarray Sums', url: 'https://leetcode.com/problems/range-sum-of-sorted-subarray-sums/', checked: false },
  { id: 62, title: 'Find K-th Smallest Pair Distance', url: 'https://leetcode.com/problems/find-k-th-smallest-pair-distance/', checked: false },
  { id: 63, title: 'Partition Array into Disjoint Intervals', url: 'https://leetcode.com/problems/partition-array-into-disjoint-intervals/', checked: false },
  { id: 64, title: 'Construct Binary Tree from Preorder and Inorder Traversal', url: 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/', checked: false },
  { id: 65, title: 'Valid Palindrome III', url: 'https://leetcode.com/problems/valid-palindrome-iii/', checked: false },
  { id: 66, title: 'Unique Paths III', url: 'https://leetcode.com/problems/unique-paths-iii/', checked: false },
  { id: 67, title: 'Stone Game II', url: 'https://leetcode.com/problems/stone-game-ii/', checked: false },
  { id: 68, title: 'Minimum Swaps to Make Sequences Increasing', url: 'https://leetcode.com/problems/minimum-swaps-to-make-sequences-increasing/', checked: false },
  { id: 69, title: 'Largest Sum of Averages', url: 'https://leetcode.com/problems/largest-sum-of-averages/', checked: false },
  { id: 70, title: 'Uncrossed Lines', url: 'https://leetcode.com/problems/uncrossed-lines/', checked: false },
  { id: 71, title: 'Number of Music Playlists', url: 'https://leetcode.com/problems/number-of-music-playlists/', checked: false },
  { id: 72, title: 'Minimum Falling Path Sum', url: 'https://leetcode.com/problems/minimum-falling-path-sum/', checked: false },
  { id: 73, title: 'Minimum Domino Rotations For Equal Row', url: 'https://leetcode.com/problems/minimum-domino-rotations-for-equal-row/', checked: false },
  { id: 74, title: 'Shortest Common Supersequence', url: 'https://leetcode.com/problems/shortest-common-supersequence/', checked: false },
  { id: 75, title: 'Sum of Subarray Minimums', url: 'https://leetcode.com/problems/sum-of-subarray-minimums/', checked: false },
  { id: 76, title: 'Maximum Points You Can Obtain from Cards', url: 'https://leetcode.com/problems/maximum-points-you-can-obtain-from-cards/', checked: false },
  { id: 77, title: 'Remove Boxes', url: 'https://leetcode.com/problems/remove-boxes/', checked: false },
  { id: 78, title: 'Unique Binary Search Trees', url: 'https://leetcode.com/problems/unique-binary-search-trees/', checked: false },
  { id: 79, title: 'Count of Range Sum', url: 'https://leetcode.com/problems/count-of-range-sum/', checked: false },
  { id: 80, title: 'First Missing Positive', url: 'https://leetcode.com/problems/first-missing-positive/', checked: false },
  { id: 81, title: '4Sum II', url: 'https://leetcode.com/problems/4sum-ii/', checked: false },
  { id: 82, title: 'Minimum Number of Arrows to Burst Balloons', url: 'https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/', checked: false },
  { id: 83, title: 'Maximum Distance in Arrays', url: 'https://leetcode.com/problems/maximum-distance-in-arrays/', checked: false },
  { id: 84, title: 'Find K Pairs with Smallest Sums', url: 'https://leetcode.com/problems/find-k-pairs-with-smallest-sums/', checked: false },
  { id: 85, title: 'Race Car', url: 'https://leetcode.com/problems/race-car/', checked: false },
  { id: 86, title: 'Minimum Cost to Merge Stones', url: 'https://leetcode.com/problems/minimum-cost-to-merge-stones/', checked: false },
  { id: 87, title: 'Longest Well-Performing Interval', url: 'https://leetcode.com/problems/longest-well-performing-interval/', checked: false },
  { id: 88, title: 'The Skyline Problem', url: 'https://leetcode.com/problems/the-skyline-problem/', checked: false },
  { id: 89, title: 'Sliding Window Median', url: 'https://leetcode.com/problems/sliding-window-median/', checked: false },
  { id: 90, title: 'Design Add and Search Words Data Structure', url: 'https://leetcode.com/problems/design-add-and-search-words-data-structure/', checked: false },
  { id: 91, title: 'Data Stream as Disjoint Intervals', url: 'https://leetcode.com/problems/data-stream-as-disjoint-intervals/', checked: false },
  { id: 92, title: 'Capacity To Ship Packages Within D Days', url: 'https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/', checked: false },
  { id: 93, title: 'Longest Subarray with Absolute Diff Less Than or Equal to Limit', url: 'https://leetcode.com/problems/longest-subarray-with-absolute-diff-less-than-or-equal-to-limit/', checked: false },
  { id: 94, title: 'Minimum Cost For Tickets', url: 'https://leetcode.com/problems/minimum-cost-for-tickets/', checked: false },
  { id: 95, title: 'Shortest Path in Binary Matrix', url: 'https://leetcode.com/problems/shortest-path-in-binary-matrix/', checked: false },
  { id: 96, title: 'Minimum Cost Tree From Leaf Values', url: 'https://leetcode.com/problems/minimum-cost-tree-from-leaf-values/', checked: false },
  { id: 97, title: 'Longest Increasing Subsequence III', url: 'https://leetcode.com/problems/longest-increasing-subsequence-iii/', checked: false },
];

export default questions;
